### ISSUE TITLE
How are deleted scalar fields (e.g. `version`) represented in the "diff" data

### ISSUE THREAD

**Issue by dpancic** [SSHOC/sshoc-marketplace-backend#152]
In GitLab by @stefanprobst on Jan 27, 2022, 11:55

e.g. the following approved item has "NEW" as the value for the `version` field:

```
curl "https://sshoc-marketplace-api.acdh-dev.oeaw.ac.at/api/tools-services/DHcf5z"
```

there is also a suggested version of that item, which has the `version` field removed:

```
curl "https://sshoc-marketplace-api.acdh-dev.oeaw.ac.at/api/tools-services/DHcf5z/versions/63912" -H "authorization: ${SSHOC_TOKEN}"
```

when querying the diff:

```
curl "https://sshoc-marketplace-api.acdh-dev.oeaw.ac.at/api/tools-services/DHcf5z/diff?with=DHcf5z&otherVersionId=63912" -H "authorization: ${SSHOC_TOKEN}"
```

the `version` field is omitted in `result.other`. it is currently unclear if this signifies that the field has been deleted, or that is is unchanged?

for comparison, this suggested version did *not* change the `version` field (the value is still "NEW"), however, here `version` is also omitted from the diff response:

```
curl "https://sshoc-marketplace-api.acdh-dev.oeaw.ac.at/api/tools-services/DHcf5z/diff?with=DHcf5z&otherVersionId=63913" -H "authorization: ${SSHOC_TOKEN}"
```

**Comment by KlausIllmayer** [comment]
Looking into this issue it seems to me, that backend already solved it (using the API endpoint for checking it):

if dateCreated/dateLastUpdated has changed, you can see the new value in the diff
if dateCreated/dateLastUpdated was deleted, it does not appear in the diff

So for this cases, @stefanprobst can you have a look if it is not implemented in frontend?

Besides, I had a problem when I tried to approve an item where only dateCreated/dateLastUpdated was deleted. I get a 500 with the error message:
```
ERROR e.s.m.c.MarketplaceExceptionHandler.handleNotModifiedException - Exception
eu.sshopencloud.marketplace.services.items.exception.VersionNotChangedException: Provided version has not changed.
at eu.sshopencloud.marketplace.services.items.ItemCrudService.updateItem(ItemCrudService.java:201)
at eu.sshopencloud.marketplace.services.items.TrainingMaterialService.updateTrainingMaterial(TrainingMaterialService.java:84)
at eu.sshopencloud.marketplace.services.items.TrainingMaterialService$$FastClassBySpringCGLIB$$1b740fe6.invoke(<generated>) 
```
@tparkola That would be something to look into (I had no problem if the dates were changed, then approve worked but in the case of deleting them this error occurs).

**Comment by tparkola** [comment]
@KlausIllmayer could you please confirm the issue you mentioned in the backend still exists (500 error). I could not replicate this bug. If you could provide step by step description - that would be very much appreciated. Thanks.

**Comment by tparkola** [comment]
OK, could you please provide step by step instruction on how to get the error? and what is the request for the diff you are trying to execute? I need some more details to verify that. As mentioned before I did checks based on what Klaus described, but could not find any problems.
