### ISSUE TITLE
Swagger file missing

### ISSUE THREAD

**Issue by KlausIllmayer** [SSHOC/sshoc-marketplace-backend#460]
The swagger file is missing. If you try to look for it on stage or on development (`/swagger-ui/index.html?url=/v3/api-docs`) you will get a status 500 with the message `No static resource swagger-ui/index.html."`
It also said so in the log files when merging the pull request 458: https://github.com/SSHOC/sshoc-marketplace-backend/pull/458#issuecomment-2336792856
```
ERROR e.s.m.c.MarketplaceExceptionHandler.handleServerException - Server Exception
org.springframework.web.servlet.resource.NoResourceFoundException: No static resource swagger-ui/index.html.
	at org.springframework.web.servlet.resource.ResourceHttpRequestHandler.handleRequest(ResourceHttpRequestHandler.java:585)
	at org.springframework.web.servlet.mvc.HttpRequestHandlerAdapter.handle(HttpRequestHandlerAdapter.java:52)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089)
```
I discovered it then but it could also has been introduced when updating to the new springboot version (see https://github.com/SSHOC/sshoc-marketplace-backend/pull/457).

@tparkola Can you check if you also miss the swagger-file on your local development instance?

**Comment by KlausIllmayer** [comment]
Swagger files are back
